spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
        - id: user_route
          #uri: http://localhost:8890
          uri: lb://users           # lb代表转发后台服务使用负载均衡,users代表服务注册中心上的服务名
          predicates:
            - Path=/user/**

        - id: product_route
          #uri: http://localhost:8888
          uri: lb://products
          predicates:
            - Path=/product/**

management:
  endpoints:
    web:
      exposure:
        include: "*"   #暴露路由规则web端点  /actuator/gateway/routes
